* #### USO DE EMACS #### 
   http://www.masteringemacs.org

** Basico
   C-g      //quit current command
   C-x z    //repite ultimo comando

** Funcionalidad de Archivos
   C-x C-f 	  //busca y abre archivo o crea uno nuevo
   C-x s	  //guarda el archivo actual del buffer
   C-x C-s	  //guarda todos los buffers
   C-x k	  //Close file or buffer

** Buffers
   C-x b	  //Switch Buffers
   C-x C-b	  //Get a List of Buffers
   C-x o	  //Switch to Other Window
   C-x 1	  //Close Other Window
   C-x 2	  //Split the Screen Horizontally
   C-x 3          //Split vertical
   C-x 0          //quita la vision actual
   
   *** Customizacion
   C-x <up>        //shrink-window
   C-x <down>      //enlarge-window
   C-x <left>      //shrink-window-horizontally
   C-x <right>     //enlarge-window-horizontally


** Edicion de Texto
   C-space	   //hace la primera marca para seleccionar texto
   M-w	           //copia texto sin borrar original
   C-w	           //copia texto borra original
   C-k             //corta hasta el final de linea
   M-k	           //borra hasta el final del parrafo (queda en kill ring)
   M-d             //borra hasta el final de la palabra
   C-y 	           //pega texto copiado, incluso desde otras ventanas
   
*** Undo
   C-x u	    //deshacer (undo)
   C-_ 	            //(redo)

** Movimientos del Cursor
   C-n	      //next line
   C-p	      //previus line
   C-a	      //principio de linea
   C-e	      //fin de linea
   M-f	      //avanzar una palabra
   M-b	      //retroceder una palabra
   M-e	      //avanza una sentencia entera
   M-a	      //retrocede una sentencia entera
   C-up/down  //avanza o retrocede un parrafo entero

   con M-x superword-mode M-f o M-b no frenan en el modo snake
    snakeMode
    snake-mode
    snake_mode    //M-f frena cursor al final en todos estos casos

** Movimientos de pagina
   C-v	          //avanza una pagina
   M-v	          //retrocede una pagina
   M->	          //final del documento
   M-<	          //principio del documento
   C-u C-space    //SALTO ATRAS (ultimo salto)
    overrided no se por quien ahora agrega un TAB (4 espacios)


** Movimientos por expresiones
   C-M-f          //proximo cierre de expresion { [ "
   C-M-b          //cierre anterior de expresion } ] "
   C-M-d          //se mueve al proximo grupo de expresiones
   C-M-u          //se mueve al grupo anterior de expresiones
   
** Indentation
   C-a M-f
   M-m
   Tab		//indent line
   C-M-\	//indent selection

** Bookmarts register
   C-x r space	//pone un bookmark
   C-x j 	//salta entre bookmarks
   C-x r m	//poner nombre al bookmark
   C-x r b	//saltar al nombre de bookmark
   C-x r l	//listar bookmarks


** TAGS
   M-,
   M-.
   M-*			//jump back
   M-x tags-apropos    	//wildcard search

** GOTO Line
   M-g g


** Conocer KeyBindings y Ayudas varias
   - M-x describe-bindings (muestra todas las combinaciones activas en el buffer)
   - M-x describe-key (poner la combinacion a averiguar)
   - C-h b bindings in the buffer
   - C-h m bindings in the modes
   - C-h w command-name  //bindings for a command
   - C-h k key-sequence  //commands for this sequence
   - C-h f function-name //si lo hago sobre el nombre lo busca por defecto
   - C-h v variable-name //si lo hago sobre el nombre lo busca por defecto
   - C-h f variable-name

** Running SHELL Comands
   M-x eshell  //ejecuta shell de emacs permite movimientos entre comandos
   M-x shell   //ejecuta un shell muy chico, envia linea completa NO permite movimeintos entre comandos
   M-x term    //ejecuta shell /bin/bash completo (no funciona en windows)
   C-c C-c     //para terminar el programa del shell o eshell
   
** Modos de edicion - Major Modes
   C-h m	     	 //lista todos los modos

** Customizaciones
~/.emacs	    //lee el la lista de customizaciones antes de arrancar

*** para customizar colores, fondo highlight
    M-x customize
    (menu-bar-mode -1)	//quita el menu en X
    (tool-bar-mode -1)	//quita los iconos en X
    (scroll-bar-mode -1)	//quita la barra lateral

*** numeros de linea
    M-x linum-mode	 	//activa los nuemeros de linea en el buffer
    M-x global-linum-mode	//activa los numeros de linea en todos los buffers
    (global-linum-mode 1)	//poner en .emacs para activar antes de entrar

*** para probar customizaciones del archivo u otro archivo, seleccionar el texto y
    M-x eval-region		     //solo parte seleccionada
    M-x eval-buffer		     //evalua todo el buffer
    C-M-x 			     //evalua solo la linea OJO no funciona
    C-x C-e    //luego de una sentencia cierre de ()evalua

*** Auto-Indent
    C-j	//activa el modo
    (define-key global-map (kbd "RET") 'newline-and-indent)	//global en .emacs


** Line endings and escape characters
   http://ergoemacs.org/emacs/emacs_line_ending_char.html
   C-q C-j pone ^J (line feed '\n')
   C-q C-m pone ^M (carriage return '\r')
   C-q C-i pone ^I (tab '\t')

* #### USO DE EMACS # OTRO MAS ####### 
  http://tuhdo.github.io/emacs-tutor.html

  C-x i pega una archivo dentro del buffer, ej test1.txt

  M-x find-file-at-point abre el archivo debajo del cursor (escrito en el text)

  M-x goto-line   ...  2
  M-x linum-mode       muestra el numero de lineas
  
  M-g g    //saltar a linea particular

  C-M-f forward-sexp adelanta en una expresion balanceada
  C-M-b backward-sexp
  C-M-k kill balanced expression
  C-M-SPC mark-sexp

  C-x C-+ agranda el tamanio de la letra
  C-x C-- achica el tamanioo de la letra
  
  C-space selecciona un area
  C-x C-x cambia el punto por la marca
  C-w borra lo seleccionado
  C-y pega lo seleccionado
  C-u 1 C-y pega uno anterior del kill-ring
  M-y pego anteriores del kill ring

** Ver el kill-ring
   C-h v kill-ring

** BOOKMARKS & Registers
   - Bookmarks
   C-x r m marca el bookmark
   C-x r b salta al bookmark TAB muestra la lista
   C-x r l lista bookmarks

   -Registers
   M-x view-register RET r  muestra el contenidode el registro r
   C-x r s r  Copy region into register r (copy-to-register) 
   C-x r i r  Insert text from register r (insert-register)

   -Register as a Bookmark
   C-x r <SPC> r  Record the position of point and the current buffer in register r (point-to-register). 
   C-x r j r  Jump to the position and buffer saved in register r (jump-to-register).

   - Guardar configuracion de windows y buffers
   C-x r w <num>    guardar confgiuracion
   C-x r j <num>    saltar a configuracion guardada
   
** COMMENTS
   M-; comenta al final de una linea o si es hay bloque marcado multiples lineas
   C-/ con una funcion propia en .emacs comenta linea o multiples lineas
   
** SEARCH
   C-s busca hacia adelante, salta con multiples C-s
   C-r busca hacia atras
   C-s C-w busca hacia adelante lo marcado por el punto, para incluir mas expresiones C-w
   C-s M-p busca entradas anteriores M-n y posteriores

   M-s .	Command: isearch-forward-symbol-at-point
                Feed the symbol at point to C-s
                perform search
   M-s o	Command: occur
                Run occur
   M-s h .	Command: highlight-symbol-at-point
                Highlight the symbol at point
   M-s h l	Command: highlight-lines-matching-regexp
                Highlight lines that match input regexp
   M-s h r	Command: highlight-regexp
                Highlight according to regexp
   M-s h u	Command: unhighlight-regexp
                Turn off highlighting strings that match
                regexp.

   M-% find and replace

** SEARCH occur
   M-x occur RET exp RET lists in a new buffer all the occurrences of the exp in the current buffer

** SEARCH IMenu
   M-x imenu	//saltar entre funciones del buffer
       TAB muestra en otro buffer las posibles opciones
       si elijo una por ejemplo m salta directo a main
       
       en python primero debo elegir la clase y luego va a la funcion

** Shell ansi-term y term
   M-x ansi-term o M-x term
   son muy parecidos, ambos tienen funcionalidad bash completa (o casi)
   C-c C-j para pasar del modo comandos (char) al modo edicion (line)
   C-c C-x para pasar del modo edicion (line) al modo comandos (char)

** #### FILE MANAGER WITH DIRED ####
   //3 formas de arrancarlo
   M-x dired
   C-x d arranca Dired en el directorio seleccionado
   C-x 4 d arranca Dired en el directorio seleccionado en otra ventana
   C-x C-f selecciona directorio para entrar con Dired
   q termina Dired
   
   n move below
   p move above
   C-s buscar con I-search
   
   f, e, RET open file at pointer
   o abrir en otra ventana
   C-o abrir en otra ventana pero no ir a la ventana
   ( listar menos informacion en el directorio
   g renueva lista
   
   d marca el archivo para borrarlo
   u desmarca archivos
   x ejecuta el borrado
   #### END DIRED ####

** #### FILE MANAGER WITH IBUFFER ####
   - Con C-x C-b aparece el ibuffer con todos los buffers que se estan usando
      incluso los que utiliza dired (mas arriba)
   - En la lista puedo buscar, ENT para elegir alguno
      d para marcar los buffers para kill, x ejecuta
   - k marca los buffers pero no hace kill, solo los saca de la lista
   - g igual que con dired actualiza la lista

** #### IDO-MODE ####
   en .emacs
      (require 'ido)
      (ido-mode t)

   //cuando trae problemas, como para crear archivo nuevo,
   C-j crea archivo con el nombre elegido (no el recomendado)
   C-f vuelve al modo find-file (without-ido-mode)
   #### END IDO-MODE ####

** #### MULTIPLE CURSORS ####
   https://github.com/magnars/multiple-cursors.el

   M-x mc/...
   ej. pinto o marco un area (palabra)
   M-x mc/mark-more-like-this-extend  y voy marcando con las flechas
   C-g deja de marcar y pasa a cursores que puedo usar todos juntos!
   //hice un override de kbd, ahora pintar letra o palabra
   C-}
   #### END MULTIPLE CURSORS ####
   
** ### Funcionalidad de paquetes
   #listar paquetes desde ELPA (por defecto)
   M-x list-packages      //'i' para marcar 'u' desmarcar 'x' hacer install
   
   #mas cantidad de repositorios, colocar esto en .emacs
   (require 'package)
   (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
   
   #cuando voy a activar los paquetes
   (package-initialize)

   #list of installed .emacs.d/elpa/*
   better-defaults
   material-theme

** #### FUNCIONALIDADES CC-MODE (major mode) ####
*** Indentation
    TAB en un renglon o region
    C-M-q (c-indent-exp) //Indents an entire balanced brace or parenthesis expression
    C-c C-q (c-indent-defun) //Indents the entire top-level function

    C-M-h (c-mark-function)

*** Comments (overrided)
    C-/  linea o region seleccionada comenta en c++ "//"

*** Movements Command
    C-M-a (c-beginning-of-defun)
    C-M-e (c-end-of-defun)

    M-a (c-beginning-of-statement)
    M-e (c-end-of-statement)

    C-c C-u (c-up-conditional)
        M-x c-up-conditional-with-else
        M-x c-down-conditional
        M-x c-down-conditional-with-else
    C-c C-p (c-backward-conditional)
    C-c C-n (c-forward-conditional)
        M-x c-backward-into-nomenclature
        M-x c-forward-into-nomenclature
    C-a overrided comienzo de linea o texto
    C-backspace hungry delete backwards (borra word anteriro y todos los espacios)
    C-delete hungry delete forwards (borra word posterior y todos los espacios)

*** Styles
    C-c . style-name <RET>

*** HideIfDef minor-mode
    M-x hide-ifdef-mode
    M-x hide-ifdefs         (oculta las definiciones que no son validas)

    C-c @           Prefix Command
    C-c @ C-d       hide-ifdef-block
    C-c @ C-q       hide-ifdef-toggle-read-only
    C-c @ C-s       show-ifdef-block
    C-c @ C-w       hide-ifdef-toggle-shadowing
    C-c @ D         hide-ifdef-set-define-alist
    C-c @ U         hide-ifdef-use-define-alist
    C-c @ d         hide-ifdef-define
    C-c @ h         hide-ifdefs
    C-c @ s         show-ifdefs
    C-c @ u         hide-ifdef-undef

** #### FUNCIONALIDAD EN PYTHON-MODE ####
*** Movimientos
    C-M-a me adelanta una funcion
    C-M-e atrasa una funcion
    C-M-n adelanta una expresion balanceada ([{
    C-M-p me atrasa una expresion balanceada }])
    //C-M-f me adelanta un condicional if: elif: else:
    //C-M-b me atrasa un condicional 
    M-a me adelanta un condicional if: elif: else:
    M-e me atrasa un condicional if: elif: else:

    con M-x superword-mode M-f o M-b no frenan en el modo snake
     snakeMode
     snake-mode
     snake_mode    //M-f frena cursor al final en todos estos casos

*** Seleccion
    C-M-SPC selecciona todo el bloque de la expresion (el punto en la primera letra de la exp)
    C-M-k borra toda la expresion (el punto en la primera letra de la exp)

*** Imenu
    M-x imenu
    con TAB me da las opciones, si la funcioesta dentro de la clase primero debo
    elegir la clase, despues lista las funciones

** #### USO GNU Global, funciona muy bien en linea de comandos!!! ####
   M-x ggtags-mode activa el modo o lo desactiva
   M-x ggtags-create-tags si el directorio-proyecto no tiene GTAGS
   M-x ggtags- TAB funciones disponibles
   M-x ggtags-find-file nombre.c busca y abre el archivo dentro del proyecto
   si en cualquier busqueda hay varios archivos/definiciones/declaraciones M-n M-p me mueve dentro de esas
   
   M-. salta entre definiciones y declaraciones
   M-* vuelve atras los saltos
   M-, vuelve atras los saltos para emacs 25

** #### SUBLIMITY MODE ####
   M-x sublimity-mode
    agrega minimap

** #### TRAMP en Emacs
   (setq tramp-default-method "ssh")
   C-x C-f /pi@192.168.1.34: RET

** DOCS
*** docs gnu-global
    https://www.gnu.org/software/global/globaldoc_toc.html
    https://github.com/leoliu/ggtags
    #ver despues para python con pygments
    #bajo paquete ggtags de melpa-stable

*** docs generales
    http://ergoemacs.org/emacs/effective_emacs.html
    https://www.emacswiki.org/emacs/IndentingC
    https://www.gnu.org/software/emacs/manual/
    https://www.gnu.org/software/emacs/manual/html_mono/ccmode.html
    http://pragmaticemacs.com/emacs/multiple-cursors/


