* Uso de Latex
** Comandos
   - para salida en la linea de comandos
     pdflatex latex.tex
     okular latex.pdf &

   - para buscar archivos de paquetes
     kpsewhich graphicx

** Download a Package
   - usa generalmente dos archivos .dtx .ins
     el primero tiene el programa y la documentacion
     el segundo la rutina para instalar

   - bajo el paquete de https://www.ctan.org/

   - descomprimo y cat README
   - ejecuto latex titling.ins, que me genera titling.sty
   - ejecuto latex titling.dtx, varias veces para generar documentacion, titling.dvi   

   - reviso donde busca el compilador los paquetes
     kpsewhich --show-path bst
   - creo el directorio local, si aun no lo tengo
     mkdir ~/texmf/tex/latex

   - copio el directorio temporal a donde latex pueda encontrarlo
     ~/texmf/tex/latex

   - ejecuto el filename database update, como usuario normal
     /usr/share/texmf/bin/mktexlsr

** Comandos Latex
   - empiezan con barra invertida \
     \begin

** Paquetes Latex
   - buscar en:
   /usr/share/texmf/tex/latex

** Comentar linea
   - uso % o %%

** Empezar documento
   - empezar con documentclass
     article para el formateo general del documento
     \documentclass{article}

   \begin{document}

   texto

   \end{document}

** Autor y titulo del documento
   - antes de begin document
     \author{MED}
     \title{Resumen Latex}

   - dentro del documento, donde quiera el titulo
     \maketitle

   - sale con la fecha actual, si la quiero cambiar fuera del documento
     \date{Hoy mismo!}

   - maketitle borra el uso de author y date, para mantener y llamarlo despues
     \makeatletter
     \author{MED}    \let\Author\@author
     \makeatother

   - lo llamo con \Author

*** titling package
   The titling package provides various user-friendly ways to modify title pages.
   It provides the macros \thetitle, \theauthor and \thedate which can be reused anywhere in your document.

*** Without Author
    \author{}

    - para evitar el espacio vacio
    \title{Prueba titles \vspace{-4ex}}

*** Multiples Autores
    \author{
    LastName1, FirstName1\\
    \texttt{first1.last1@xxxxx.com}
    \and
    LastName2, FirstName2\\
    \texttt{first2.last2@xxxxx.com}
    }
    \title{Usage of the \texttt{\textbackslash author} command}

    \begin{document}
    \maketitle
    \end{document}

*** Mejores titulos
    https://en.wikibooks.org/wiki/LaTeX/Title_Creation

*** Subtitle
    - la clase de documento articulo no tiene macro \subtitle, se lo puede agregar 
      directamente dentro de \title
    \title{Title \\ Subtitle}

    - se puede definir el documento como scrartcl que si tiene macro \subtitle
      \documentclass{scrartcl}


** Latex
   {\LaTeX}

** Secciones y subsecciones
   \section{Introduccion}
   \subsection{intro 2}
   \section*{Intro}    #para evitar el numero del indice

** Bold Italic Enfasis Underline
   \textbf{texto en negrita}
   \textit{texto italic}
   \emph{otro texto en italic}
   \underline{texto subrayado}

** Comillas
   " son siempre comillas de cierre
   `` son comillas de apertura
   '' son comillas de cierre

** Acentos
   - los acentos se pueden incluir como \'a
   - o directamente en el texto incluyendo el paquete
     \usepackage[utf8]{inputenc}

     \usepackage[latin1]{inputenc}

   Cuando no hay más remedio, los caracteres extendidos se escriben así:
   
   á  ==>  \'a        Á  ==>  \'A     ñ  ==>  \~n   ¿  ==>  ?`
   é  ==>  \'e        É  ==>  \'E     Ñ  ==>  \~N   ¡  ==>  !`
   í  ==>  \'\i{}     Í  ==>  \'I     ü  ==>  \"u
   ó  ==>  \'o        Ó  ==>  \'O     Ü  ==>  \"U
   ú  ==>  \'u        Ú  ==>  \'U   

** Indentar - Sangria
   - Indentar esta activo por default en los parrafos, excepto luego de una \section
     porque en ingles no se indenta la primer linea.
   - al final del parrafo dos enters o \par

   - En un parrafo puedo empezar con \indent

*** Tamanio del Indent
    - el tamanio del indent lo puedo modificar con
    \setlength\parindent{24pt}

*** Si no quiero indentar un parrafo
    \noindent

*** Indentar luego de una Section
    \usepackage{indentfirst}

** Listas
*** Lista numerada
   - empiezo y termino la lista
     \begin{enumerate}
     \end{enumerate}

*** Lista sin numeros
    \begin{itemize}
    \end{ítemize}

   - items de la lista
     \item pan
     \item manteca
     \item leche
     \item huevos

** Nombres y referencias
   - para agregar un nombre a una seccion lo hago con el comando label
     \setion{Lista\label{lista1}}

   - para llamar a la referencia desde el texto lo hago con ref
     que me va a remplazar la referecnia con el indice que tenga Lista
     \ref{lista1}

   - generalmente hay que compilar 2 veces para que reemplaze correctamente

** Archivo de bibliografia
   - usa biber, no esta por default en slackware
   
   - antes del documento llamar al paquete
     \usepackage{biblatex}

     \usepackage[backend=biber]{biblatex}
     \addbibresource{uni.bib}

     \usepackage[backend=biber, style=authoryear-icomp]{biblatex}

     #uni.bib es el documento con toda la bibliografia

   - poner documentos, articulos, libros, etc
     @book{sist_cont,
     author = "Smith, Luke",
     title = "First bokk!",
     year = "2018",
     publisher = "algun loquito"
     }

     lo llamo con el primer label sist_cont
     
   - donde quiera las referencias de bibliografia
     \printbibliography

   - en alguna linea dentro del documento
     as \textcite{sist_cont} el numero debe ser...
     as \parencite{sist_cont} el numero debe ser...

*** Comandos
    compilo con pdflatex sin el tipo de archivo??
    llamo a biber sin el tipo de archivo
    compilo nuevamente

    pdflatex latex1
    biber latex1
    pdflatex latex

** Cambiar el formato fuera del documento
*** Titulo
    \usepackage{titlesec}

    \titleformat{\section}
    {\huge}    #formatting \huge \bfseries \lowercase
    {}        #numbering \thesection $\bullet$
    {0em}    #distancia entre el numero y el texto es obligatorio
    {}        #entre el numer y el texto, lo que sea va aca

    {}[\titlerule]        #en el ultimo argumento le agrego una barra al final

*** Subtitulo
    - llamar al mismo comando pero en las subsecciones
    \titleformat{\subsection}      
      
*** Sin indentar
    \titleformat{\subsection}[runin]

*** Cambiar titulo con funcion \renewcommand y paquete titling
    \renewcommand{maketitle}{}

    \usepackage{titling}

**** Ejemplo
    \renewcommand{maketitle}
    {
    \begin{center}
    {\huge\bfseries
    \theauthor}


    \end{center}
    }

*** Espaciado de las secciones
    \titlespacing{subsubsection}
    {0em}    #left margin
    {0em}    #espaciado vertical
    {0em}    #espaciado luego de la subsection antes del parrafo, horizontal si uso runin o vertical

** Espaciado vertical
   \vspace{.25em}

** Completado de espacios
   - para empujar todo a la derecha
     \hfill

** Linea vertical
   - con \vline
   \hfill\vline\hfill

** Mayusculas grandes y chicas Small Caps
   \textsc{deleu}    #va a salir todo en mayusculas de diferente altura

** Salto de pagina
   \pagebreak

** Margenes y tamanio de hoja
   - uso el paquete geometry

   \usepackage{geometry}

   \usepackage[margin=1in]{geometry}

** Imagenes
   con el paquete graphicx
   \usepackage{graphicx}

   en el documento
   \includegraphics{archivo.png}

   \begin{center}
   \includegraphics[width=2in]{archivo.png}
   \end{center}

   \includegraphics[scale=0.5]{archivo.png}

   \includegraphics[width=\textwidth]{archivo.png}

   \includegraphics[width=0.7\textwidth]{archivo.png}

** Basics of Labels and Referencing
   \label{marker}
   The marker can be seen as a name that we give to the object that we want to reference. 
   It's important to add \label after a numbered element e.g. *\section, \subsection, \caption* etc, 
   otherwise the label won't "latch on" to the correct number or counter.

   \ref{marker}
   This prints the number assigned to the object labeled by marker.

   \pageref{marker}
   This prints the number of the page where the object labeled by marker appears.

** Bibliografia simple
   - https://en.wikibooks.org/wiki/LaTeX/Bibliography_Management
   - antes del final del documento \end{document}
   \begin{thebibliography}{9}

   \bibitem{lamport94}
   Leslie Lamport,
   \textit{\LaTeX: a document preparation system},
   Addison Wesley, Massachusetts,
   2nd edition,
  1994.

  \end{thebibliography}

  - lo llamo con \cite{cite_key}

*** Otro simple
    \begin{thebibliography}{1}

    \bibitem{notes} John W. Dower {\em Readings compiled for History
    21.479.}  1991.

    \bibitem{impj}  The Japan Reader {\em Imperial Japan 1800-1945} 1973:
    Random House, N.Y.

    \bibitem{norman} E. H. Norman {\em Japan's emergence as a modern
    state} 1940: International Secretariat, Institute of Pacific
    Relations.

    \bibitem{fo} Bob Tadashi Wakabayashi {\em Anti-Foreignism and Western
    Learning in Early-Modern Japan} 1986: Harvard University Press.

    \end{thebibliography}

** Figuras
   - mismo paquete anterior, le agrega nombre y ajusta en el texto
     ademas la acomoda en la hoja independiente de donde se llame, donde le parezca que queda mejor

   \begin{figure}
   \begin{center}
   \includegraphics[width=0.7\textwidth]{fig1.png}
   \end{center}
   \caption{Esta es la maldita figura}
   \end{figure}

   - si lo quiero en ese exacto lugar \begin{figure}[h!]
     para referenciarlo ~\ref{fig:maldita}

   \begin{figure}[h!]
   \includegraphics[width=0.7\textwidth]{fig1.png}
   \caption{Esta es la maldita figura}
   \label{fig:maldita}
   \end{figure}

*** Modificadores []
h	Place the float here, i.e., approximately at the same point it occurs in the source text (however, not exactly at the spot)
t	Position at the top of the page.
b	Position at the bottom of the page.
p	Put on a special page for floats only.
!	Override internal parameters LaTeX uses for determining "good" float positions.
H	Places the float at precisely the location in the LaTeX code. 
        Requires the float package,[1] i.e., \usepackage{float}. USAR ESTE SI QUIERO LA FOTO JUSTO AHI

** Figuras mezcladas con texto - o texto y texto - label y ref
   - usa lel paquete wrapfig
     \usepackage{wrapfig}

   \begin{wrapfigure}{r}{3in}        #en la derecha y el tamanio
   \centering
   \includegraphics[width=2.5in]{fig2.png}
   \caption{Esta es la maldita figura}
   \end{wrapfigure}

*** Label y ref
    - en la figura

   \begin{wrapfigure}{r}{3in}        #en la derecha y el tamanio
   \centering
   \includegraphics[width=2.5in]{fig2.png}
   \caption{Esta es la maldita figura\label{prueba_fig}}
   \end{wrapfigure}

   - en el documento
     please refer to \ref{prueba_fig}

** Funciones NEWCOMMAND
   - toma dos argumentos 
     \newcommand{\nombre_cmd}{lo que hace}

   - mas argumentos para pasar al comando, n el numero de comandos
     \newcommand{\nombre_cmd}[n]{lo que hace}

   - recupero los argumentos con #n, #1, #2

** Minipages
   - para definir el formato de una parte de la pagina
     \begin{minipage}[t]{.15\textwidth}
     \end{minipage}

   - dos minipage pegadas deben salir en columna mientras no se supere \textwith, pero
     no me funciona

** Columnas
   - pruebo con tablas
     \begin{tabular}{ l r }
   \includegraphics[width=0.35\textwidth]{images/induction_motor.jpg} &
   \includegraphics[width=0.55\textwidth]{images/auxiliary_winding_scheme.png}\\  
   \end{tabular}

** HyperLinks
   - uso el paquete hyperref que me permite manipular los links
     \usepackage{hyperref}

     \hyperref[label_name]{''link text''}

     \href{<my_url>}{<description>}

     \url{<my_url>}

** Matematica y Formulas
   To print your equations in display mode use one of these delimiters:
   \[ \], $$ $$, \begin{displaymath} \end{displaymath} or 
   \begin{equation} \end{equation}

*** Punto para multipliar
    \cdot

*** Subscripts and superscripts
   cos-1 --> cos^{-1}

   cos \phi_{sc}

*** Letras griegas, operadores y otros
    Greek letters	\alpha \beta \gamma \rho \sigma \delta \epsilon
                        \Omega \omega

    Binary operators	\times \otimes \oplus \cup \cap

    Relation operators	< > \subset \supset \subseteq \supseteq

    Others	\int \oint \sum \prod

*** Inline
    This formula $f(x) = x^2$ is an example.

*** En el centro de la hoja
    $$E=mc^2$$

*** Ecuaciones y entornos alineados
    \usepackage{amsmath}

    \begin{document}

    \begin{equation*}
    1 + 2 = 3 
    \end{equation*}

    \begin{equation*}
    1 = 3 - 2
    \end{equation*}

    - la alineacion la consigo con el &
    \begin{align*}
    1 + 2 &= 3\\
    1 &= 3 - 2
    \end{align*}

*** Fracciones
    \usepackage{amsmath}

    \begin{document}

    \begin{align*}
    f(x) &= x^2\\
    g(x) &= \frac{1}{x}\\
    F(x) &= \int^a_b \frac{1}{3}x^3
    \end{align*}

    \frac{1}{\sqrt{x}}

*** Integrales
    \int_lowerbound^upperbound

    $\int_a^b f(x)dx$

\begin{equation*}
  ta = \int_0^{nr} \frac {2\pi(Jm - Jl)} {60(CM - CL)} dn
\end{equation*}

*** Matrices
    - usar paquetes anteriores
    \begin{matrix}
    1 & 0\\
    0 & 1
    \end{matrix}

    - con corchetes
      [
    \begin{matrix}
    1 & 0\\
    0 & 1
    \end{matrix}
    ]

    - con corchetes escalados
      \left[
    \begin{matrix}
    1 & 0\\
    0 & 1
    \end{matrix}
    \right]

*** Paretesis escalados
    \left(\frac{1}{\sqrt{x}}\right)

** Tablas
   - & separa campos, \\nueva fila, l left, c center, r right para cada columna
   
   - con lineas verticales entre ellas |
   \begin{tabular}{ l | c | r }
   1 & 2 & 3 \\
   4 & 5 & 6 \\
   7 & 8 & 9 \\
   \end{tabular}

   - sin lineas verticales    
   \begin{tabular}{ l c r }

   - con lineas horizontales
     \hline 

   - con espacios específicos With width specified:
   \begin{center}
   \begin{tabular}{ | l | l | l | p{5cm} |}
   \hline
   Day & Min Temp & Max Temp & Summary \\ \hline


** Código dentro del archivo
   - con el paquete \usepackage{listings}

   \begin{lstlisting}    
   #include "utils.h"
   
   int al_cubo (int a)
   {
   return (int) (a*a*a);
   }
   \end{lstlisting}

** Presentaciones con Beamer
   https://www.youtube.com/watch?v=zEjBCQhND2c&index=8&list=PL-p5XmQHB_JSQvW8_mhBdcwEyxdVX0c1T

   \documentclass{beamer}

   \usethem{Frankfurt}

*** Slides
    \begin{frame}
    \end{frame}
     
*** Sections
    las sections forman links a cada slide
    \section{explicacion}

*** Texto en Columnas
    - esto es para el sistema de presentaciones [beamer]
    \begin{columns}
    \column{.5\textwidth}
    texto
    \column{.5\textwidth}
    otro texto
    \end{columns}



