* PARA UTILIZAR SCRIPTS PYTHON EN SLACKWARE

#puedo correr scripts desde la consola con python y el nombre del script
pyhton test.py

#si corro el script dentro del interprete las variables quedan cargadas y las puede revisar despues
#puedo correr el script dentro del interprete python con la funcion execfile
python
>>> execfile ('test.py')
>>> var_value
>>> quit()

#Si lo quiero correr dentro del interprete y pasarle argumentos
#En el script incluir sys para poder recuperar los argumentos
import sys

if len(sys.argv) != 2:
    	print 'usage : and one more arg'
    	sys.exit(1)

#en el interprete
>>> import sys
>>> sys.argv = ['arg1', 'arg2']
>>> execfile('test.py')

* USOS de PIP (pip3)
** Buscar programa o libreria en PyPi
   # pip3 search pyside2

** Upgrade de PiP
   # pip3 install --upgrade pip

* Scientific Python

** Matplotlib
*** Format Strings
    A format string consists of a part for color, marker and line:

    fmt = '[marker][line][color]'
    Copy to clipboard
    Each of them is optional. If not provided, the value from the style cycle is used. Exception: If line is given, but no marker, the data will be a line without markers.

    Other combinations such as [color][marker][line] are also supported, but note that their parsing may be ambiguous.

**** Markers
     character	description
     '.'	    point marker
     ','	    pixel marker
     'o'	    circle marker
     'v'	    triangle_down marker
     '^'	    triangle_up marker
     '<'	    triangle_left marker
     '>'	    triangle_right marker
     '1'	    tri_down marker
     '2'	    tri_up marker
     '3'	    tri_left marker
     '4'	    tri_right marker
     's'	    square marker
     'p'	    pentagon marker
     '*'	    star marker
     'h'	    hexagon1 marker
     'H'	    hexagon2 marker
     '+'	    plus marker
     'x'	    x marker
     'D'	    diamond marker
     'd'	    thin_diamond marker
     '|'	    vline marker
     '_'	    hline marker

**** Line Styles
     character	description
     '-'	    solid line style
     '--'    dashed line style
     '-.'    dash-dot line style
     ':'	    dotted line style

     Example format strings:

     'b'    # blue markers with default shape
     'or'   # red circles
     '-g'   # green solid line
     '--'   # dashed line with default color
     '^k:'  # black triangle_up markers connected by a dotted line

**** Colors
     The supported color abbreviations are the single letter codes

     character	color
     'b'	blue
     'g'	green
     'r'	red
     'c'	cyan
     'm'	magenta
     'y'	yellow
     'k'	black
     'w'	white
     
     and the 'CN' colors that index into the default property cycle.
     If the color is the only part of the format string, you can additionally
     use any matplotlib.colors spec, e.g. full names ('green') or hex strings ('#008000').
